export { default as Landing } from './Landing'
export { default as About } from './About'
export { default as DoctorProfile } from './Doctor/DoctorProfile'
export { default as Service } from './Service'
export { default as Contact } from './Contact'