export { default as Hero } from './Hero'
export { default as Advance } from './Advance'
export { default as ListDoctor } from './ListDoctor'
export { default as Services } from './Services'
export { default as HowItWorks } from './HowItWorks'
